export default {
    MARK_NOTIFICATION:'MARK_NOTIFICATION',
    MARK_ALL_NOTFICATIONS:'MARK_ALL_NOTIFICATIONS',
    START_MARK:'START_MARK',
    FINISH_MARK:'FINISH_MARK',
    GET_NOTIFICATIONS_LIST:'GET_NOTIFICATIONS_LIST',
    START_LOGIN:'START_LOGIN',
    LOGIN_SUCCESS:"LOGIN_SUCCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
    LOGOUT:"LOGOUT"
}


