"""empty message

Revision ID: 37a5a533c51b
Revises: 1212565e11b4
Create Date: 2019-12-12 01:31:28.829119

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '37a5a533c51b'
down_revision = '1212565e11b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
