"""empty message

Revision ID: 6bbaa13dbd68
Revises: d94d55864470
Create Date: 2019-12-09 23:47:14.970547

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6bbaa13dbd68'
down_revision = 'd94d55864470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
