# Generated by Django 2.2.3 on 2019-08-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'AI策略',
                'verbose_name_plural': 'AI策略',
            },
        ),
        migrations.CreateModel(
            name='TraditionalSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '传统策略',
                'verbose_name_plural': '传统策略',
            },
        ),
    ]
